name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout nightly
        run: rustup update nightly && rustup default nightly
      - name: Install cargo-expand
        run: cargo install cargo-expand
      - name: Build easy_switch
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
